name: documentation release

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
    tags:
      - '*'


permissions:
  contents: write

jobs:
  test:
    name: Documentation
    runs-on: ubuntu-latest
    steps:
      - name: Install system packages
        run: |
          sudo apt-get update -y
          sudo apt-get install -y libgl1 libglx-mesa0 libgl1-mesa-dev libglu1-mesa-dev freeglut3-dev libosmesa6 libosmesa6-dev libgles2-mesa-dev libarchive-dev libpangocairo-1.0-0

      - name: checkout actions
        uses: actions/checkout@v4

      - uses: mamba-org/setup-micromamba@v1
        with:
          micromamba-version: '1.5.8-0' # any version from https://github.com/mamba-org/micromamba-releases
          environment-file: environment_dev.yml
          init-shell: bash
          cache-environment: true
          post-cleanup: 'all'

      - name: install dependencies
        shell: bash -el {0}
        run: python -m pip install .[docs]
      
      - name: Sphinx build tagged version
        if: startsWith(github.ref, 'refs/tags/')
        shell: bash -el {0}
        run: |
          sphinx-build docs _build/${{ github.ref_name }}
          rm -rf _build/stable
          mkdir -p _build/stable
          sphinx-build -b linkcheck docs _build/stable
        
      - name: Sphinx build dev version
        if: (github.event_name == 'push' || github.event_name == 'pull_request') && !startsWith(github.ref, 'refs/tags/')
        shell: bash -el {0}
        run: |
          rm -rf _build/dev
          mkdir -p _build/dev
          sphinx-build -b linkcheck docs _build/dev

      - name: Deploy docs to GitHub Pages
        if: github.event_name == 'push' || startsWith(github.ref, 'refs/tags/')
        uses: peaceiris/actions-gh-pages@v4
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _build
          # with next rlease of actions-gh-pages
          # issue to allow force_orphan will be fixed
          # https://github.com/peaceiris/actions-gh-pages/issues/455
          # force_orphan: true
          keep_files: true
